// Generated by CoffeeScript 1.9.3
(function() {
  jQuery(function($) {
    return $("#excelUploader").change(function() {
      var data;
      data = new FormData;
      data.append($(this).attr('name'), this.files[0]);
      data.append('directionId', $("#directionId").val());
      return $.ajax({
        url: '/backend/parser/process',
        type: 'POST',
        data: data,
        cache: false,
        processData: false,
        contentType: false,
        context: this,
        dataType: 'json',
        success: function(data) {
          return $("#parse-result").html(data.map(function(item) {
            return $("<tr></tr>").append([$("<td></td>").text(item.direction), $("<td></td>").text(item.name), $("<td></td>").text(item.price), $("<td></td>").text(item.status)]);
          }));
        }
      });
    });
  });

}).call(this);

//# sourceMappingURL=parser.js.map
