// Generated by CoffeeScript 1.9.3
(function() {
  jQuery(function($) {
    $('.first-upper').magnificPopup({
      delegate: 'a',
      type: 'image',
      gallery: {
        enabled: true
      }
    });
    $('.first-down').magnificPopup({
      delegate: 'a',
      type: 'image',
      gallery: {
        enabled: true
      }
    });
    $('.second').magnificPopup({
      delegate: 'a',
      type: 'image',
      gallery: {
        enabled: true
      }
    });
    return $('.slick-about-magnific').magnificPopup({
      delegate: 'a',
      type: 'image',
      gallery: {
        enabled: true
      }
    });
  });

}).call(this);

//# sourceMappingURL=about.js.map
