// Generated by CoffeeScript 1.9.3
(function() {
  jQuery(function($) {
    var contactAddWrapper, contactInnerButton, hoverAddContainer;
    contactInnerButton = $(".contacts-submit");
    contactAddWrapper = $(".contacts-hover-wrapper-add");
    hoverAddContainer = ".hover-add-container";
    contactInnerButton.click(function() {
      contactAddWrapper.show();
      return contactInnerButton.toggleClass("activeContactAdd");
    });
    return contactAddWrapper.click(function(e) {
      if (!$(e.target).parents().is(hoverAddContainer)) {
        $(this).hide();
      }
      return contactInnerButton.toggleClass("activeContactAdd");
    });
  });

}).call(this);

//# sourceMappingURL=contacts.js.map
