// Generated by CoffeeScript 1.9.3
(function() {
  $(document).ready(function() {
    var commentTabs;
    commentTabs = $(".doctor-buttons").find("div");
    return commentTabs.click(function(e) {
      var clicked, comment, content, parentContent;
      clicked = $(this);
      content = $("." + clicked.find("section").data("href"));
      clicked.find(".doctor-show-resume").toggleClass("active-show-resume");
      e.stopPropagation();
      e.preventDefault();
      content.parent().slideToggle(200);
      comment = content.find(".doctor-comments-wrapper");
      parentContent = clicked.parent().closest("section");
      parentContent.toggleClass("parent-active");
      if (!comment.hasClass("slick-slide")) {
        return content.find(".doctor-comments-wrapper").slick({
          dots: false,
          infinite: false,
          speed: 300,
          slidesToShow: 1,
          slidesToScroll: 1,
          responsive: [
            {
              breakpoint: 1024,
              settings: {
                slidesToShow: 1,
                slidesToScroll: 1,
                infinite: true,
                dots: true
              }
            }, {
              breakpoint: 600,
              settings: {
                slidesToShow: 1,
                slidesToScroll: 2
              }
            }, {
              breakpoint: 480,
              settings: {
                slidesToShow: 1,
                slidesToScroll: 1
              }
            }
          ]
        });
      }
    });
  });

  jQuery(function($) {
    var doctorAddWrapper, doctorCommentsForm, doctorInnerButton, hoverAddContainer, successMessasge;
    doctorInnerButton = $(".doctor-add");
    doctorAddWrapper = $(".doctor-add-hover-wrapper-add");
    hoverAddContainer = ".hover-add-container";
    successMessasge = $(".success-message");
    doctorCommentsForm = $(".form-doctor-comment");
    doctorInnerButton.click(function() {
      var clicked, directionInput, doctorDirectionInput, doctorInput, doctorNameInput, parentContent;
      clicked = $(this);
      doctorAddWrapper.show();
      doctorInnerButton.toggleClass("activeDoctorAdd");
      parentContent = clicked.parent().closest("section");
      $('.doctor-one').removeClass("parent-active-button");
      parentContent.addClass("parent-active-button");
      doctorNameInput = $("#doctors .parent-active-button .doctor-add").find(".getDoctorVal");
      doctorDirectionInput = $("#doctors .parent-active-button .doctor-add").find(".getDirectionVal");
      doctorInput = $(".form-hover-doctor-val");
      directionInput = $(".form-hover-direction-val");
      doctorInput.val(doctorNameInput.val());
      return directionInput.val(doctorDirectionInput.val());
    });
    doctorAddWrapper.click(function(e) {
      if (!$(e.target).parents().is(hoverAddContainer)) {
        $(this).hide();
      }
      return doctorInnerButton.toggleClass("activeDoctorAdd");
    });
    $(".form-doctor-rating").on('mouseover mouseout', '.doctor-star', function() {
      return $(this).prevAll(".doctor-star").toggleClass("active");
    }).on('click', '.doctor-star', function() {
      $(".fixed").removeClass("fixed");
      $(".input-doctor-rating").val($(this).data("value"));
      return $(this).addClass("fixed").prevAll(".doctor-star").addClass("fixed");
    });
    doctorCommentsForm.submit(function(e) {
      var form;
      e.preventDefault();
      form = $(this);
      return $.post(this.action, form.serialize(), function(response) {
        var data, error, i, len, ref, results;
        data = JSON.parse(response);
        if (data.type === 'success') {
          successMessasge.show();
          return setTimeout(function() {
            doctorCommentsForm[0].reset();
            return successMessasge.hide();
          }, 4000);
        } else {
          ref = data.errors;
          results = [];
          for (i = 0, len = ref.length; i < len; i++) {
            error = ref[i];
            results.push($(".comment-" + error).addClass("error"));
          }
          return results;
        }
      });
    });
    return doctorCommentsForm.on('focus', '.error', function() {
      return $(this).removeClass('error');
    });
  });

}).call(this);

//# sourceMappingURL=doctors.js.map
