// Generated by CoffeeScript 1.9.3
(function() {
  jQuery(function($) {
    var hoverAddContainer, questionAddWrapper, questionButton;
    questionButton = $("#nav-footer-question");
    questionAddWrapper = $(".question-wrapper-add");
    hoverAddContainer = ".hover-add-container";
    questionButton.click(function() {
      questionAddWrapper.show();
      return questionButton.toggleClass("nav-footer-question-active");
    });
    return questionAddWrapper.click(function(e) {
      if (!$(e.target).parents().is(hoverAddContainer)) {
        $(this).hide();
      }
      return questionButton.toggleClass("nav-footer-question-active");
    });
  });

}).call(this);

//# sourceMappingURL=footer.js.map
