// Generated by CoffeeScript 1.9.3
(function() {
  jQuery(function($) {
    var form, formAddBlog, formComplexDiscount, formDoctorAnonim, formFooterQuestion, formFree, formFreeHover, formHoverContact, formSignDirection, formSignDirectionDoctor, formSignDirectionSympt, formSignHeader, formSpecialOffer, formStaticCall, formStaticQuestion, getHiddenLang;
    getHiddenLang = $('.getHiddenLang').val();
    form = $("#form-inspection");
    form.submit(function(e) {
      var styleSelected;
      e.preventDefault();
      styleSelected = $('#form-inspection .styledSelect');
      $('#direction-form-name-2').val(styleSelected.text());
      return $.post(form.attr('action'), form.serialize(), function(resp) {
        var error, i, len, ref, results;
        if (resp.type === 'success') {
          form.get(0).reset();
          return setTimeout(function() {
            return window.location.href = "/" + getHiddenLang + "/thanks";
          }, 1500);
        } else {
          ref = resp.errors;
          results = [];
          for (i = 0, len = ref.length; i < len; i++) {
            error = ref[i];
            results.push($(".form-inspection-" + error).addClass('error'));
          }
          return results;
        }
      }, 'json');
    });
    form.on('focus', '.error', function() {
      return $(this).removeClass('error');
    });
    formFree = $("#form-free-consult");
    formFree.submit(function(e) {
      var styleSelected;
      e.preventDefault();
      styleSelected = $('#form-free-consult .styledSelect');
      $('#direction-form-name-4').val(styleSelected.text());
      return $.post(formFree.attr('action'), formFree.serialize(), function(resp) {
        var error, i, len, ref, results;
        if (resp.type === 'success') {
          formFree.get(0).reset();
          return setTimeout(function() {
            return window.location.href = "/" + getHiddenLang + "/thanks";
          }, 1500);
        } else {
          ref = resp.errors;
          results = [];
          for (i = 0, len = ref.length; i < len; i++) {
            error = ref[i];
            results.push($(".form-free-consult-" + error).addClass('error'));
          }
          return results;
        }
      }, 'json');
    });
    formFree.on('focus', '.error', function() {
      return $(this).removeClass('error');
    });
    formFreeHover = $("#form-index-consult");
    formFreeHover.submit(function(e) {
      var styleSelected;
      e.preventDefault();
      styleSelected = $('#form-index-consult .styledSelect');
      $('#direction-form-name-3').val(styleSelected.text());
      return $.post(formFreeHover.attr('action'), formFreeHover.serialize(), function(resp) {
        var error, i, len, ref, results;
        if (resp.type === 'success') {
          formFreeHover.get(0).reset();
          return setTimeout(function() {
            return window.location.href = "/" + getHiddenLang + "/thanks";
          }, 1500);
        } else {
          ref = resp.errors;
          results = [];
          for (i = 0, len = ref.length; i < len; i++) {
            error = ref[i];
            results.push($(".form-hover-add-" + error).addClass('error'));
          }
          return results;
        }
      }, 'json');
    });
    formFreeHover.on('focus', '.error', function() {
      return $(this).removeClass('error');
    });
    formFooterQuestion = $("#form-hover-footer-question");
    formFooterQuestion.submit(function(e) {
      e.preventDefault();
      return $.post(formFooterQuestion.attr('action'), formFooterQuestion.serialize(), function(resp) {
        var error, i, len, ref, results;
        if (resp.type === 'success') {
          formFooterQuestion.get(0).reset();
          return setTimeout(function() {
            return window.location.href = "/" + getHiddenLang + "/thanks";
          }, 1500);
        } else {
          ref = resp.errors;
          results = [];
          for (i = 0, len = ref.length; i < len; i++) {
            error = ref[i];
            results.push($(".form-hover-footer-" + error).addClass('error'));
          }
          return results;
        }
      }, 'json');
    });
    formFooterQuestion.on('focus', '.error', function() {
      return $(this).removeClass('error');
    });
    formAddBlog = $("#form-hover-addDoctor-blog");
    formAddBlog.submit(function(e) {
      var styleSelected;
      e.preventDefault();
      styleSelected = $('#form-hover-addDoctor-blog .styledSelect');
      $('#direction-form-name-5').val(styleSelected.text());
      return $.post(formAddBlog.attr('action'), formAddBlog.serialize(), function(resp) {
        var error, i, len, ref, results;
        if (resp.type === 'success') {
          formAddBlog.get(0).reset();
          return setTimeout(function() {
            return window.location.href = "/" + getHiddenLang + "/thanks";
          }, 1500);
        } else {
          ref = resp.errors;
          results = [];
          for (i = 0, len = ref.length; i < len; i++) {
            error = ref[i];
            results.push($(".form-hover-blog-add-" + error).addClass('error'));
          }
          return results;
        }
      }, 'json');
    });
    formAddBlog.on('focus', '.error', function() {
      return $(this).removeClass('error');
    });
    formHoverContact = $("#form-contacts");
    formHoverContact.submit(function(e) {
      e.preventDefault();
      return $.post(formHoverContact.attr('action'), formHoverContact.serialize(), function(resp) {
        var error, i, len, ref, results;
        if (resp.type === 'success') {
          formHoverContact.get(0).reset();
          return setTimeout(function() {
            return window.location.href = "/" + getHiddenLang + "/thanks";
          }, 1500);
        } else {
          ref = resp.errors;
          results = [];
          for (i = 0, len = ref.length; i < len; i++) {
            error = ref[i];
            results.push($(".form-hover-add-contact-" + error).addClass('error'));
          }
          return results;
        }
      }, 'json');
    });
    formHoverContact.on('focus', '.error', function() {
      return $(this).removeClass('error');
    });
    formSignHeader = $("#form-inspection-header");
    formSignHeader.submit(function(e) {
      var styleSelected;
      e.preventDefault();
      styleSelected = $('#form-inspection-header .styledSelect');
      $('#direction-form-name').val(styleSelected.text());
      return $.post(formSignHeader.attr('action'), formSignHeader.serialize(), function(resp) {
        var error, i, len, ref, results;
        if (resp.type === 'success') {
          formSignHeader.get(0).reset();
          return setTimeout(function() {
            return window.location.href = "/" + getHiddenLang + "/thanks";
          }, console.log("/" + getHiddenLang + "/thanks"), 1500);
        } else {
          ref = resp.errors;
          results = [];
          for (i = 0, len = ref.length; i < len; i++) {
            error = ref[i];
            results.push($(".form-inspection-header-" + error).addClass('error'));
          }
          return results;
        }
      }, 'json');
    });
    formSignHeader.on('focus', '.error', function() {
      return $(this).removeClass('error');
    });
    formComplexDiscount = $("#form-hover-add");
    formComplexDiscount.submit(function(e) {
      e.preventDefault();
      return $.post(formComplexDiscount.attr('action'), formComplexDiscount.serialize(), function(resp) {
        var error, i, len, ref, results;
        if (resp.type === 'success') {
          formComplexDiscount.get(0).reset();
          return setTimeout(function() {
            return window.location.href = "/" + getHiddenLang + "/thanks";
          }, 1500);
        } else {
          ref = resp.errors;
          results = [];
          for (i = 0, len = ref.length; i < len; i++) {
            error = ref[i];
            results.push($(".form-complex-discount-" + error).addClass('error'));
          }
          return results;
        }
      }, 'json');
    });
    formComplexDiscount.on('focus', '.error', function() {
      return $(this).removeClass('error');
    });
    formSignDirection = $("#form-hover-add-diagnostic");
    formSignDirection.submit(function(e) {
      e.preventDefault();
      return $.post(formSignDirection.attr('action'), formSignDirection.serialize(), function(resp) {
        var error, i, len, ref, results;
        if (resp.type === 'success') {
          formSignDirection.get(0).reset();
          return setTimeout(function() {
            return window.location.href = "/" + getHiddenLang + "/thanks";
          }, 1500);
        } else {
          ref = resp.errors;
          results = [];
          for (i = 0, len = ref.length; i < len; i++) {
            error = ref[i];
            results.push($(".form-sign-direction-" + error).addClass('error'));
          }
          return results;
        }
      }, 'json');
    });
    formSignDirection.on('focus', '.error', function() {
      return $(this).removeClass('error');
    });
    formSignDirectionSympt = $("#form-hover-add-symptoms");
    formSignDirectionSympt.submit(function(e) {
      e.preventDefault();
      return $.post(formSignDirectionSympt.attr('action'), formSignDirectionSympt.serialize(), function(resp) {
        var error, i, len, ref, results;
        if (resp.type === 'success') {
          formSignDirectionSympt.get(0).reset();
          return setTimeout(function() {
            return window.location.href = "/" + getHiddenLang + "/thanks";
          }, 1500);
        } else {
          ref = resp.errors;
          results = [];
          for (i = 0, len = ref.length; i < len; i++) {
            error = ref[i];
            results.push($(".form-sign-direction-" + error).addClass('error'));
          }
          return results;
        }
      }, 'json');
    });
    formSignDirectionSympt.on('focus', '.error', function() {
      return $(this).removeClass('error');
    });
    formSignDirectionDoctor = $("#form-hover-add-doctor");
    formSignDirectionDoctor.submit(function(e) {
      e.preventDefault();
      return $.post(formSignDirectionDoctor.attr('action'), formSignDirectionDoctor.serialize(), function(resp) {
        var error, i, len, ref, results;
        if (resp.type === 'success') {
          formSignDirectionDoctor.get(0).reset();
          return setTimeout(function() {
            return window.location.href = "/" + getHiddenLang + "/thanks";
          }, 1500);
        } else {
          ref = resp.errors;
          results = [];
          for (i = 0, len = ref.length; i < len; i++) {
            error = ref[i];
            results.push($(".form-sign-direction-" + error).addClass('error'));
          }
          return results;
        }
      }, 'json');
    });
    formSignDirectionDoctor.on('focus', '.error', function() {
      return $(this).removeClass('error');
    });
    formDoctorAnonim = $("#form-hover-add-question");
    formDoctorAnonim.submit(function(e) {
      e.preventDefault();
      return $.post(formDoctorAnonim.attr('action'), formDoctorAnonim.serialize(), function(resp) {
        var error, i, len, ref, results;
        if (resp.type === 'success') {
          formDoctorAnonim.get(0).reset();
          return setTimeout(function() {
            return window.location.href = "/" + getHiddenLang + "/thanks";
          }, 1500);
        } else {
          ref = resp.errors;
          results = [];
          for (i = 0, len = ref.length; i < len; i++) {
            error = ref[i];
            results.push($(".form-hover-question-dir-" + error).addClass('error'));
          }
          return results;
        }
      }, 'json');
    });
    formDoctorAnonim.on('focus', '.error', function() {
      return $(this).removeClass('error');
    });
    formSpecialOffer = $("#form-discount-add-doctor");
    formSpecialOffer.submit(function(e) {
      var offerInput, offerNameInput;
      offerNameInput = $("#slick-special-wrapper .slick-active .special-content-get-discount").find(".getDiscountVal");
      offerInput = $(".form-hover-offer-val");
      offerInput.val(offerNameInput.val());
      e.preventDefault();
      return $.post(formSpecialOffer.attr('action'), formSpecialOffer.serialize(), function(resp) {
        var error, i, len, ref, results;
        if (resp.type === 'success') {
          formSpecialOffer.get(0).reset();
          return setTimeout(function() {
            return window.location.href = "/" + getHiddenLang + "/thanks";
          }, 1500);
        } else {
          ref = resp.errors;
          results = [];
          for (i = 0, len = ref.length; i < len; i++) {
            error = ref[i];
            results.push($(".form-direction-discount-offer-" + error).addClass('error'));
          }
          return results;
        }
      }, 'json');
    });
    formSpecialOffer.on('focus', '.error', function() {
      return $(this).removeClass('error');
    });
    formStaticQuestion = $("#form-static-add-question");
    formStaticQuestion.submit(function(e) {
      e.preventDefault();
      return $.post(formStaticQuestion.attr('action'), formStaticQuestion.serialize(), function(resp) {
        var error, i, len, ref, results;
        if (resp.type === 'success') {
          formStaticQuestion.get(0).reset();
          return setTimeout(function() {
            return window.location.href = "/" + getHiddenLang + "/thanks";
          }, 1500);
        } else {
          ref = resp.errors;
          results = [];
          for (i = 0, len = ref.length; i < len; i++) {
            error = ref[i];
            results.push($(".form-hover-question-dir-" + error).addClass('error'));
          }
          return results;
        }
      }, 'json');
    });
    formStaticQuestion.on('focus', '.error', function() {
      return $(this).removeClass('error');
    });
    formStaticCall = $("#form-call-static");
    formStaticCall.submit(function(e) {
      e.preventDefault();
      return $.post(formStaticCall.attr('action'), formStaticCall.serialize(), function(resp) {
        var error, i, len, ref, results;
        if (resp.type === 'success') {
          formStaticCall.get(0).reset();
          return setTimeout(function() {
            return window.location.href = "/" + getHiddenLang + "/thanks";
          }, 1500);
        } else {
          ref = resp.errors;
          results = [];
          for (i = 0, len = ref.length; i < len; i++) {
            error = ref[i];
            results.push($(".form-hover-add-contact-" + error).addClass('error'));
          }
          return results;
        }
      }, 'json');
    });
    formStaticCall.on('focus', '.error', function() {
      return $(this).removeClass('error');
    });
    $(".form-inspection-doctor").find(".styledSelect").click(function(e) {
      e.stopPropagation();
      return $(".form-inspection-doctor").removeClass('error');
    });
    return $(".mask-phone-input").mask("+38(999) 999-99-99");
  });

}).call(this);

//# sourceMappingURL=forms.js.map
