// Generated by CoffeeScript 1.9.3
(function() {
  $(document).ready(function() {
    var addHoverButton, addHoverWrapper, addSignButton, addSignWrapper, addStatic, callStaticButton, callStaticWrapper, containerStatic, homeSubNavItem, hoverAddContainer, questionStaticButton, questionWrapper, staticButtons, staticHeader, subNavDom, subNavDom2;
    subNavDom = $('.header-nav-item .header-subNav-item-hidden .header-subNavChildren-item p');
    subNavDom2 = $('.header-subNavChildren-hidden a');
    staticHeader = $("#header-static-hide");
    homeSubNavItem = $(".only-home-subNav");
    $('.header-nav-item .header-subNav-item').click(function() {
      $(this).toggleClass("colorWhite");
      $(this).parent().toggleClass("borderNone");
      $(this).parent().find('.header-subNavChildren-item').slideToggle(200);
      return $('.header-subNavChildren-hidden').hide();
    });
    subNavDom.click(function() {
      var parent, subParent;
      subParent = $(this).parent().closest("div");
      parent = subParent.parent().closest("div");
      return parent.find('.header-subNavChildren-hidden').slideToggle(200);
    });
    subNavDom2.click(function() {
      return staticHeader.toggleClass("click-active-static-header");
    });
    $('.header-nav-item .header-subNav-item-hidden .header-subNavChildren-hidden a').click(function(e) {
      e.stopPropagation();
      $('#hamburgNav').toggleClass("active-hamburg-menu");
      return $('.wrapper-content').toggleClass("hidden-wrapper");
    });
    homeSubNavItem.click(function(e) {
      e.stopPropagation();
      $('#hamburgNav').toggleClass("active-hamburg-menu");
      return $('.wrapper-content').toggleClass("hidden-wrapper");
    });
    $('.header-menu-icon, #close-header-menu').click(function(e) {
      var parent, parentItem, section, sectionHref, subParent;
      e.stopPropagation();
      $('#hamburgNav').toggleClass("active-hamburg-menu");
      $('.wrapper-content').toggleClass("hidden-wrapper");
      subParent = subNavDom.parent().closest("div");
      parent = subParent.parent().closest("div");
      parentItem = parent.parent().closest("div");
      parentItem.addClass("active-subNav-children");
      parent.addClass("active-subNavChild");
      section = parent.find('.header-subNavChildren-hidden');
      sectionHref = section.find('a');
      staticHeader.toggleClass("click-active-static-header");
      return sectionHref.click(function() {
        sectionHref.removeClass("sectionHref");
        return $(this).addClass("sectionHref");
      });
    });
    $('.wrapper').on("click", ".hidden-wrapper", function() {
      $('#hamburgNav').toggleClass("active-hamburg-menu");
      $('.wrapper-content').toggleClass("hidden-wrapper");
      return staticHeader.toggleClass("click-active-static-header");
    });
    addHoverButton = $(".header-blog-inner-button");
    addHoverWrapper = $(".addDoctor-blog-hover-wrapper");
    questionStaticButton = $(".static-question");
    questionWrapper = $(".question-static-wrapper-add");
    callStaticButton = $(".static-call");
    callStaticWrapper = $(".static-call-wrapper-add");
    hoverAddContainer = ".hover-add-container";
    addHoverButton.click(function() {
      addHoverWrapper.show();
      return addHoverButton.toggleClass("activeBlogInner");
    });
    addHoverWrapper.click(function(e) {
      if (!$(e.target).parents().is(hoverAddContainer)) {
        $(this).hide();
      }
      return addHoverButton.toggleClass("activeBlogInner");
    });
    questionStaticButton.click(function() {
      questionWrapper.show();
      return questionStaticButton.toggleClass("activeBlogInner");
    });
    questionWrapper.click(function(e) {
      if (!$(e.target).parents().is(hoverAddContainer)) {
        $(this).hide();
      }
      questionStaticButton.toggleClass("activeBlogInner");
      return staticHeader.removeClass('not-show-header-static');
    });
    callStaticButton.click(function() {
      callStaticWrapper.show();
      return callStaticButton.toggleClass("activeBlogInner");
    });
    callStaticWrapper.click(function(e) {
      if (!$(e.target).parents().is(hoverAddContainer)) {
        $(this).hide();
      }
      callStaticButton.toggleClass("activeBlogInner");
      return staticHeader.removeClass('not-show-header-static');
    });
    addSignButton = $(".header-menu-button-add");
    addSignWrapper = $(".headerAddMenu-wrapper");
    addStatic = $(".static-add");
    containerStatic = $(".container-static-buttons");
    staticButtons = $(".static-add, .static-question, .static-call");
    addSignButton.click(function() {
      addSignWrapper.show();
      return addSignButton.toggleClass("activeHeaderAdd");
    });
    addStatic.click(function() {
      addSignWrapper.show();
      return addSignButton.toggleClass("activeBlogInner");
    });
    staticButtons.click(function() {
      staticButtons.addClass('active-static-click');
      return staticHeader.addClass('not-show-header-static');
    });
    return addSignWrapper.click(function(e) {
      if (!$(e.target).parents().is(hoverAddContainer)) {
        $(this).hide();
      }
      addSignButton.toggleClass("activeHeaderAdd");
      staticButtons.removeClass('active-static-click');
      return staticHeader.removeClass('not-show-header-static');
    });
  });

}).call(this);

//# sourceMappingURL=header-menu.js.map
