// Generated by CoffeeScript 1.9.3
(function() {
  jQuery(function($) {
    var newsHiddenHoverSub, newsHiddenLinks, newsHiddenSubIcon;
    $("#newsMore").click(function(e) {
      var offset, side;
      offset = $("#newsOffset");
      side = $("#newsSide");
      e.preventDefault();
      e.stopPropagation();
      return $.getJSON('/news/more', {
        offset: offset.val(),
        side: side.val()
      }, (function(_this) {
        return function(resp) {
          $(resp.more).appendTo($("#newsContainer")).slideDown();
          offset.val(parseInt(offset.val()) + 1);
          side.val(function() {
            if (side.val() === '0') {
              return 1;
            } else {
              return 0;
            }
          });
          if (!resp.larger) {
            $(_this).hide();
          }
          return $(".nav-pager").find(".news-numbers.active").last().next().addClass('active');
        };
      })(this));
    });
    $(".nav-pager").on("click", ".active", function(e) {
      return e.preventDefault();
    });
    newsHiddenLinks = $('.news-hidden-links');
    newsHiddenHoverSub = $('.news-hidden-hover-sub');
    newsHiddenSubIcon = $('.news-hidden-subIcon');
    return $('.news-hidden-hover .news-hidden-hover-sub').click(function() {
      newsHiddenLinks.hide();
      newsHiddenHoverSub.removeClass("prevDiv");
      newsHiddenSubIcon.removeClass("prev");
      $(this).parent().find('.news-hidden-links').show();
      $(this).parent().find('.news-hidden-hover-sub').addClass("prevDiv");
      return $(this).parent().find('.news-hidden-subIcon').addClass("prev");
    });
  });

}).call(this);

//# sourceMappingURL=news.js.map
